// Mocks generated by Mockito 5.4.4 from annotations
// in mobile/test/helpers/helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:graphql_flutter/graphql_flutter.dart' as _i3;
import 'package:mobile/features/job/business/entities/job_entity.dart' as _i4;
import 'package:mobile/features/job/business/repos/job_repo.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [JobRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockJobRepo extends _i1.Mock implements _i2.JobRepo {
  MockJobRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  dynamic getJobs(_i3.QueryOptions<Object?>? options) =>
      super.noSuchMethod(Invocation.method(
        #getJobs,
        [options],
      ));

  @override
  dynamic getJob(String? id) => super.noSuchMethod(Invocation.method(
        #getJob,
        [id],
      ));

  @override
  dynamic createJob(_i3.MutationOptions<Object?>? options) =>
      super.noSuchMethod(Invocation.method(
        #createJob,
        [options],
      ));

  @override
  dynamic updateJob(
    String? id,
    _i4.JobEntity? job,
  ) =>
      super.noSuchMethod(Invocation.method(
        #updateJob,
        [
          id,
          job,
        ],
      ));

  @override
  dynamic deleteJob(_i3.MutationOptions<Object?>? options) =>
      super.noSuchMethod(Invocation.method(
        #deleteJob,
        [options],
      ));
}
